{{ if .Values.sql.runCreationScripts }}
kind: Job
apiVersion: batch/v1
metadata:
  name: sql-create-emds
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: initial-creator
          image: {{ .Values.sql.creationScriptImage }}
          args:
            - /Action:Publish
            - /SourceFile:/elektrawebdb/EMDS/EMDS.dacpac
            - /TargetServerName:tcp:{{ .Values.sql.connection.server }},{{ .Values.sql.connection.port }}
            - /TargetUser:{{ .Values.sql.connection.user }}
            - /TargetPassword:{{ .Values.sql.connection.password }}
            - /TargetDatabaseName:{{ .Values.dbNames.EMDS }}
            - /Variables:ZDB01={{ .Values.dbNames.ZDB01 }}
            - /Variables:DDLEVENTS={{ .Values.dbNames.DDLEVENTS }}
            - /Variables:ERSDEVELOPER={{ .Values.dbNames.ERSDEVELOPER }}
            - /Variables:EMDS_LOGS={{ .Values.dbNames.EMDS_LOGS }}
            - /Variables:master=master
            - /Variables:msdb=msdb
{{ end }}
