{{ if .Values.channelManager.install }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: channelmanager
  labels:
    k8s-app: channelmanager
spec:
  selector:
    matchLabels:
      k8s-app: channelmanager
  template:
    metadata:
      name: channelmanager
      labels:
        k8s-app: channelmanager
    spec:
      containers:
        - name: channelmanager
          image: ghcr.io/travelaps/channelmanager:latest
          env:
            - name: CONNECTIONSTRING
              value: >-
                Data Source=TCP:sql,1433;Initial Catalog=EMDS;Persist
                Security Info=False;User
                ID=sa;Password={{ .Values.sql.saPassword }};Connection
                Timeout=60;MultipleActiveResultSets=True;Pooling=False;Application
                Name=ChmSync;
      imagePullSecrets:
        - name: regcred
{{ end }}
